var annotated_dup =
[
    [ "Captain", "namespaceCaptain.html", [
      [ "DMode", "namespaceCaptain_1_1DMode.html", [
        [ "DriveModel", "classCaptain_1_1DMode_1_1DriveModel.html", "classCaptain_1_1DMode_1_1DriveModel" ],
        [ "IAutomaticallyDeactivated", "classCaptain_1_1DMode_1_1IAutomaticallyDeactivated.html", "classCaptain_1_1DMode_1_1IAutomaticallyDeactivated" ],
        [ "IMultipleVehicleTrackable", "classCaptain_1_1DMode_1_1IMultipleVehicleTrackable.html", "classCaptain_1_1DMode_1_1IMultipleVehicleTrackable" ],
        [ "CF", "classCaptain_1_1DMode_1_1CF.html", "classCaptain_1_1DMode_1_1CF" ],
        [ "AdjSpeed", "classCaptain_1_1DMode_1_1AdjSpeed.html", "classCaptain_1_1DMode_1_1AdjSpeed" ],
        [ "CV", "classCaptain_1_1DMode_1_1CV.html", "classCaptain_1_1DMode_1_1CV" ],
        [ "BLC", "classCaptain_1_1DMode_1_1BLC.html", "classCaptain_1_1DMode_1_1BLC" ],
        [ "DLC", "classCaptain_1_1DMode_1_1DLC.html", "classCaptain_1_1DMode_1_1DLC" ],
        [ "ELC", "classCaptain_1_1DMode_1_1ELC.html", "classCaptain_1_1DMode_1_1ELC" ],
        [ "ALC", "classCaptain_1_1DMode_1_1ALC.html", "classCaptain_1_1DMode_1_1ALC" ],
        [ "Stay", "classCaptain_1_1DMode_1_1Stay.html", "classCaptain_1_1DMode_1_1Stay" ],
        [ "ApproachStation", "classCaptain_1_1DMode_1_1ApproachStation.html", "classCaptain_1_1DMode_1_1ApproachStation" ],
        [ "CCF", "classCaptain_1_1DMode_1_1CCF.html", "classCaptain_1_1DMode_1_1CCF" ],
        [ "MCF", "classCaptain_1_1DMode_1_1MCF.html", "classCaptain_1_1DMode_1_1MCF" ],
        [ "LaneKeeping", "classCaptain_1_1DMode_1_1LaneKeeping.html", "classCaptain_1_1DMode_1_1LaneKeeping" ],
        [ "Stop", "classCaptain_1_1DMode_1_1Stop.html", "classCaptain_1_1DMode_1_1Stop" ]
      ] ],
      [ "Node", "namespaceCaptain_1_1Node.html", [
        [ "GarageUnit", "classCaptain_1_1Node_1_1GarageUnit.html", "classCaptain_1_1Node_1_1GarageUnit" ],
        [ "ILinkable", "structCaptain_1_1Node_1_1ILinkable.html", "structCaptain_1_1Node_1_1ILinkable" ],
        [ "IVehicleContainableUnit", "structCaptain_1_1Node_1_1IVehicleContainableUnit.html", "structCaptain_1_1Node_1_1IVehicleContainableUnit" ],
        [ "IntersectionMicroLink", "classCaptain_1_1Node_1_1IntersectionMicroLink.html", "classCaptain_1_1Node_1_1IntersectionMicroLink" ],
        [ "MesoLink", "classCaptain_1_1Node_1_1MesoLink.html", "classCaptain_1_1Node_1_1MesoLink" ],
        [ "MesoUnit", "classCaptain_1_1Node_1_1MesoUnit.html", "classCaptain_1_1Node_1_1MesoUnit" ],
        [ "MicroLane", "classCaptain_1_1Node_1_1MicroLane.html", "classCaptain_1_1Node_1_1MicroLane" ],
        [ "MicroLink", "classCaptain_1_1Node_1_1MicroLink.html", "classCaptain_1_1Node_1_1MicroLink" ],
        [ "SinkUnit", "classCaptain_1_1Node_1_1SinkUnit.html", "classCaptain_1_1Node_1_1SinkUnit" ],
        [ "SourceUnit", "classCaptain_1_1Node_1_1SourceUnit.html", "classCaptain_1_1Node_1_1SourceUnit" ],
        [ "Station", "classCaptain_1_1Node_1_1Station.html", "classCaptain_1_1Node_1_1Station" ],
        [ "UniformIntersectionLink", "classCaptain_1_1Node_1_1UniformIntersectionLink.html", "classCaptain_1_1Node_1_1UniformIntersectionLink" ],
        [ "UniformLink", "classCaptain_1_1Node_1_1UniformLink.html", "classCaptain_1_1Node_1_1UniformLink" ],
        [ "UnitConnectionInfo", "structCaptain_1_1Node_1_1UnitConnectionInfo.html", "structCaptain_1_1Node_1_1UnitConnectionInfo" ]
      ] ],
      [ "Util", "namespaceCaptain_1_1Util.html", [
        [ "EventRecorder", "classCaptain_1_1Util_1_1EventRecorder.html", "classCaptain_1_1Util_1_1EventRecorder" ],
        [ "EventRecorderContainer", "structCaptain_1_1Util_1_1EventRecorderContainer.html", "structCaptain_1_1Util_1_1EventRecorderContainer" ],
        [ "JsonReader", "classCaptain_1_1Util_1_1JsonReader.html", "classCaptain_1_1Util_1_1JsonReader" ],
        [ "JsonWriter", "classCaptain_1_1Util_1_1JsonWriter.html", "classCaptain_1_1Util_1_1JsonWriter" ],
        [ "VehicleQueue", "classCaptain_1_1Util_1_1VehicleQueue.html", "classCaptain_1_1Util_1_1VehicleQueue" ],
        [ "XmlWriter", "classCaptain_1_1Util_1_1XmlWriter.html", "classCaptain_1_1Util_1_1XmlWriter" ]
      ] ],
      [ "Engine", "classCaptain_1_1Engine.html", "classCaptain_1_1Engine" ],
      [ "IEventRecordable", "structCaptain_1_1IEventRecordable.html", "structCaptain_1_1IEventRecordable" ],
      [ "DriveModeDescriptor", "classCaptain_1_1DriveModeDescriptor.html", "classCaptain_1_1DriveModeDescriptor" ],
      [ "Position", "structCaptain_1_1Position.html", "structCaptain_1_1Position" ],
      [ "Message", "structCaptain_1_1Message.html", "structCaptain_1_1Message" ],
      [ "LinkLanePair", "structCaptain_1_1LinkLanePair.html", "structCaptain_1_1LinkLanePair" ],
      [ "UnitPosition", "structCaptain_1_1UnitPosition.html", "structCaptain_1_1UnitPosition" ],
      [ "MicroLinkEventInfo", "structCaptain_1_1MicroLinkEventInfo.html", "structCaptain_1_1MicroLinkEventInfo" ],
      [ "SegmentInfo", "structCaptain_1_1SegmentInfo.html", "structCaptain_1_1SegmentInfo" ],
      [ "MicroLinkInfo", "structCaptain_1_1MicroLinkInfo.html", "structCaptain_1_1MicroLinkInfo" ],
      [ "MesoLinkInfo", "structCaptain_1_1MesoLinkInfo.html", "structCaptain_1_1MesoLinkInfo" ],
      [ "VehicleRecordInfo", "structCaptain_1_1VehicleRecordInfo.html", "structCaptain_1_1VehicleRecordInfo" ],
      [ "CellRecordInfo", "structCaptain_1_1CellRecordInfo.html", "structCaptain_1_1CellRecordInfo" ],
      [ "StationRecordInfo", "structCaptain_1_1StationRecordInfo.html", "structCaptain_1_1StationRecordInfo" ],
      [ "SinkRecordInfo", "structCaptain_1_1SinkRecordInfo.html", "structCaptain_1_1SinkRecordInfo" ],
      [ "SimulationRecordInfo", "structCaptain_1_1SimulationRecordInfo.html", "structCaptain_1_1SimulationRecordInfo" ],
      [ "pair_hash", "structCaptain_1_1pair__hash.html", "structCaptain_1_1pair__hash" ],
      [ "tuple_hash", "structCaptain_1_1tuple__hash.html", "structCaptain_1_1tuple__hash" ],
      [ "microLinkEventInfoCompare", "structCaptain_1_1microLinkEventInfoCompare.html", "structCaptain_1_1microLinkEventInfoCompare" ],
      [ "UnitIdentifierMap", "structCaptain_1_1UnitIdentifierMap.html", "structCaptain_1_1UnitIdentifierMap" ],
      [ "Passenger", "classCaptain_1_1Passenger.html", "classCaptain_1_1Passenger" ],
      [ "PublicTransitInfo", "structCaptain_1_1PublicTransitInfo.html", "structCaptain_1_1PublicTransitInfo" ],
      [ "VehicleReservationInfo", "classCaptain_1_1VehicleReservationInfo.html", "classCaptain_1_1VehicleReservationInfo" ],
      [ "PassengerReservationInfo", "classCaptain_1_1PassengerReservationInfo.html", "classCaptain_1_1PassengerReservationInfo" ],
      [ "Route", "structCaptain_1_1Route.html", "structCaptain_1_1Route" ],
      [ "PaxRoute", "structCaptain_1_1PaxRoute.html", "structCaptain_1_1PaxRoute" ],
      [ "RouteIdentifier", "structCaptain_1_1RouteIdentifier.html", "structCaptain_1_1RouteIdentifier" ],
      [ "UnitIdentifier", "structCaptain_1_1UnitIdentifier.html", "structCaptain_1_1UnitIdentifier" ],
      [ "UnitConnectionDescriptor", "structCaptain_1_1UnitConnectionDescriptor.html", "structCaptain_1_1UnitConnectionDescriptor" ],
      [ "V2X", "classCaptain_1_1V2X.html", "classCaptain_1_1V2X" ],
      [ "Vehicle", "classCaptain_1_1Vehicle.html", "classCaptain_1_1Vehicle" ],
      [ "VehicleInfo", "structCaptain_1_1VehicleInfo.html", "structCaptain_1_1VehicleInfo" ],
      [ "VehicleState", "structCaptain_1_1VehicleState.html", "structCaptain_1_1VehicleState" ],
      [ "VehicleDescriptor", "structCaptain_1_1VehicleDescriptor.html", "structCaptain_1_1VehicleDescriptor" ],
      [ "VehicleRoute", "structCaptain_1_1VehicleRoute.html", "structCaptain_1_1VehicleRoute" ],
      [ "ConcurrentQueue", "classCaptain_1_1ConcurrentQueue.html", "classCaptain_1_1ConcurrentQueue" ],
      [ "MesoComputationModel", "structCaptain_1_1MesoComputationModel.html", "structCaptain_1_1MesoComputationModel" ],
      [ "BasicMesoModel", "structCaptain_1_1BasicMesoModel.html", "structCaptain_1_1BasicMesoModel" ],
      [ "RandomEngine", "classCaptain_1_1RandomEngine.html", "classCaptain_1_1RandomEngine" ],
      [ "RandomDistribution", "classCaptain_1_1RandomDistribution.html", "classCaptain_1_1RandomDistribution" ],
      [ "NormalDistribution", "classCaptain_1_1NormalDistribution.html", "classCaptain_1_1NormalDistribution" ],
      [ "UniformDistribution", "classCaptain_1_1UniformDistribution.html", "classCaptain_1_1UniformDistribution" ],
      [ "ExponentialDistribution", "classCaptain_1_1ExponentialDistribution.html", "classCaptain_1_1ExponentialDistribution" ],
      [ "PoissonDistribution", "classCaptain_1_1PoissonDistribution.html", "classCaptain_1_1PoissonDistribution" ],
      [ "SharedObjectInfo", "structCaptain_1_1SharedObjectInfo.html", "structCaptain_1_1SharedObjectInfo" ],
      [ "WeakPtr", "classCaptain_1_1WeakPtr.html", "classCaptain_1_1WeakPtr" ],
      [ "SharedPtr", "classCaptain_1_1SharedPtr.html", "classCaptain_1_1SharedPtr" ],
      [ "SpinLock", "classCaptain_1_1SpinLock.html", "classCaptain_1_1SpinLock" ],
      [ "SharedSpinlock", "classCaptain_1_1SharedSpinlock.html", null ],
      [ "SpinLockQueue", "classCaptain_1_1SpinLockQueue.html", "classCaptain_1_1SpinLockQueue" ],
      [ "SpinLockVehicleQueue", "classCaptain_1_1SpinLockVehicleQueue.html", "classCaptain_1_1SpinLockVehicleQueue" ],
      [ "IVehicleQueue", "classCaptain_1_1IVehicleQueue.html", "classCaptain_1_1IVehicleQueue" ]
    ] ],
    [ "NextSimIO", "namespaceNextSimIO.html", [
      [ "MetaData", "classNextSimIO_1_1MetaData.html", "classNextSimIO_1_1MetaData" ],
      [ "InputAgents", "classNextSimIO_1_1InputAgents.html", "classNextSimIO_1_1InputAgents" ],
      [ "InputCell", "classNextSimIO_1_1InputCell.html", "classNextSimIO_1_1InputCell" ],
      [ "InputDistribution", "classNextSimIO_1_1InputDistribution.html", "classNextSimIO_1_1InputDistribution" ],
      [ "InputEvent", "classNextSimIO_1_1InputEvent.html", "classNextSimIO_1_1InputEvent" ],
      [ "InputFlow", "classNextSimIO_1_1InputFlow.html", "classNextSimIO_1_1InputFlow" ],
      [ "InputLane", "classNextSimIO_1_1InputLane.html", "classNextSimIO_1_1InputLane" ],
      [ "InputLink", "classNextSimIO_1_1InputLink.html", "classNextSimIO_1_1InputLink" ],
      [ "InputMessage", "classNextSimIO_1_1InputMessage.html", "classNextSimIO_1_1InputMessage" ],
      [ "InputMode", "classNextSimIO_1_1InputMode.html", "classNextSimIO_1_1InputMode" ],
      [ "InputNode", "classNextSimIO_1_1InputNode.html", "classNextSimIO_1_1InputNode" ],
      [ "InputODMatrix", "classNextSimIO_1_1InputODMatrix.html", "classNextSimIO_1_1InputODMatrix" ],
      [ "InputODPax", "classNextSimIO_1_1InputODPax.html", "classNextSimIO_1_1InputODPax" ],
      [ "InputAgentPax", "classNextSimIO_1_1InputAgentPax.html", "classNextSimIO_1_1InputAgentPax" ],
      [ "InputPTline", "classNextSimIO_1_1InputPTline.html", "classNextSimIO_1_1InputPTline" ],
      [ "InputSegment", "classNextSimIO_1_1InputSegment.html", "classNextSimIO_1_1InputSegment" ],
      [ "InputStation", "classNextSimIO_1_1InputStation.html", "classNextSimIO_1_1InputStation" ],
      [ "InputDRTStation", "classNextSimIO_1_1InputDRTStation.html", "classNextSimIO_1_1InputDRTStation" ],
      [ "InputVehicleTypes", "classNextSimIO_1_1InputVehicleTypes.html", "classNextSimIO_1_1InputVehicleTypes" ],
      [ "connection", "classNextSimIO_1_1connection.html", "classNextSimIO_1_1connection" ],
      [ "intersectionPhase", "classNextSimIO_1_1intersectionPhase.html", "classNextSimIO_1_1intersectionPhase" ],
      [ "port", "classNextSimIO_1_1port.html", "classNextSimIO_1_1port" ],
      [ "AgentsArr", "classNextSimIO_1_1AgentsArr.html", "classNextSimIO_1_1AgentsArr" ],
      [ "EventArr", "classNextSimIO_1_1EventArr.html", "classNextSimIO_1_1EventArr" ],
      [ "LinkArr", "classNextSimIO_1_1LinkArr.html", "classNextSimIO_1_1LinkArr" ],
      [ "MessageArr", "classNextSimIO_1_1MessageArr.html", "classNextSimIO_1_1MessageArr" ],
      [ "ModeArr", "classNextSimIO_1_1ModeArr.html", "classNextSimIO_1_1ModeArr" ],
      [ "NodeArr", "classNextSimIO_1_1NodeArr.html", "classNextSimIO_1_1NodeArr" ],
      [ "ODMatrixArr", "classNextSimIO_1_1ODMatrixArr.html", "classNextSimIO_1_1ODMatrixArr" ],
      [ "ParamArr", "classNextSimIO_1_1ParamArr.html", "classNextSimIO_1_1ParamArr" ],
      [ "PaxArr", "classNextSimIO_1_1PaxArr.html", "classNextSimIO_1_1PaxArr" ],
      [ "PTlineArr", "classNextSimIO_1_1PTlineArr.html", "classNextSimIO_1_1PTlineArr" ],
      [ "ScenarioArr", "classNextSimIO_1_1ScenarioArr.html", "classNextSimIO_1_1ScenarioArr" ],
      [ "StationArr", "classNextSimIO_1_1StationArr.html", "classNextSimIO_1_1StationArr" ],
      [ "VehicleTypesArr", "classNextSimIO_1_1VehicleTypesArr.html", "classNextSimIO_1_1VehicleTypesArr" ]
    ] ],
    [ "ODMatrix", "classODMatrix.html", null ]
];