var hierarchy =
[
    [ "NextSimIO::AgentsArr", "classNextSimIO_1_1AgentsArr.html", null ],
    [ "NextSimIO::ArcArr", "classNextSimIO_1_1ArcArr.html", null ],
    [ "NextSimIO::ArcCost", "classNextSimIO_1_1ArcCost.html", null ],
    [ "NextSimIO::BackgroundTrafficArr", "classNextSimIO_1_1BackgroundTrafficArr.html", null ],
    [ "Communication", "classCommunication.html", null ],
    [ "Captain::ConcurrentQueue< T >", "classCaptain_1_1ConcurrentQueue.html", null ],
    [ "NextSimIO::connection", "classNextSimIO_1_1connection.html", null ],
    [ "NextSimIO::ConnectionInfo", "classNextSimIO_1_1ConnectionInfo.html", null ],
    [ "DriveMode", "classDriveMode.html", null ],
    [ "Captain::DriveModeDescriptor", "classCaptain_1_1DriveModeDescriptor.html", null ],
    [ "Captain::DMode::DriveModel", "classCaptain_1_1DMode_1_1DriveModel.html", [
      [ "Captain::DMode::ALC", "classCaptain_1_1DMode_1_1ALC.html", null ],
      [ "Captain::DMode::AdjSpeed", "classCaptain_1_1DMode_1_1AdjSpeed.html", null ],
      [ "Captain::DMode::ApproachStation", "classCaptain_1_1DMode_1_1ApproachStation.html", null ],
      [ "Captain::DMode::BLC", "classCaptain_1_1DMode_1_1BLC.html", null ],
      [ "Captain::DMode::CCF", "classCaptain_1_1DMode_1_1CCF.html", null ],
      [ "Captain::DMode::CF", "classCaptain_1_1DMode_1_1CF.html", null ],
      [ "Captain::DMode::CV", "classCaptain_1_1DMode_1_1CV.html", null ],
      [ "Captain::DMode::DLC", "classCaptain_1_1DMode_1_1DLC.html", null ],
      [ "Captain::DMode::ELC", "classCaptain_1_1DMode_1_1ELC.html", null ],
      [ "Captain::DMode::LaneKeeping", "classCaptain_1_1DMode_1_1LaneKeeping.html", null ],
      [ "Captain::DMode::MCF", "classCaptain_1_1DMode_1_1MCF.html", null ],
      [ "Captain::DMode::Stay", "classCaptain_1_1DMode_1_1Stay.html", null ],
      [ "Captain::DMode::Stop", "classCaptain_1_1DMode_1_1Stop.html", null ]
    ] ],
    [ "Captain::Engine", "classCaptain_1_1Engine.html", null ],
    [ "EventActionType", "classEventActionType.html", null ],
    [ "NextSimIO::EventArr", "classNextSimIO_1_1EventArr.html", null ],
    [ "Captain::Util::EventRecorder", "classCaptain_1_1Util_1_1EventRecorder.html", null ],
    [ "Captain::Util::EventRecorderContainer", "structCaptain_1_1Util_1_1EventRecorderContainer.html", null ],
    [ "NextSimIO::exit", "classNextSimIO_1_1exit.html", null ],
    [ "NextSimIO::Graph", "classNextSimIO_1_1Graph.html", null ],
    [ "Captain::DMode::IAutomaticallyDeactivated", "classCaptain_1_1DMode_1_1IAutomaticallyDeactivated.html", [
      [ "Captain::DMode::AdjSpeed", "classCaptain_1_1DMode_1_1AdjSpeed.html", null ],
      [ "Captain::DMode::ApproachStation", "classCaptain_1_1DMode_1_1ApproachStation.html", null ],
      [ "Captain::DMode::Stay", "classCaptain_1_1DMode_1_1Stay.html", null ]
    ] ],
    [ "Captain::IEventRecordable", "structCaptain_1_1IEventRecordable.html", [
      [ "Captain::Network::MesoUnit", "classCaptain_1_1Network_1_1MesoUnit.html", null ],
      [ "Captain::Network::MicroLane", "classCaptain_1_1Network_1_1MicroLane.html", null ],
      [ "Captain::Network::RailStation", "classCaptain_1_1Network_1_1RailStation.html", null ],
      [ "Captain::Network::RoadStation", "classCaptain_1_1Network_1_1RoadStation.html", null ]
    ] ],
    [ "Captain::Network::ILinkable", "structCaptain_1_1Network_1_1ILinkable.html", [
      [ "Captain::Network::MesoLink", "classCaptain_1_1Network_1_1MesoLink.html", null ],
      [ "Captain::Network::MicroLink", "classCaptain_1_1Network_1_1MicroLink.html", [
        [ "Captain::Network::IntersectionMicroLink", "classCaptain_1_1Network_1_1IntersectionMicroLink.html", null ]
      ] ],
      [ "Captain::Network::UniformLink", "classCaptain_1_1Network_1_1UniformLink.html", [
        [ "Captain::Network::UniformIntersectionLink", "classCaptain_1_1Network_1_1UniformIntersectionLink.html", null ]
      ] ]
    ] ],
    [ "Captain::DMode::IMultipleVehicleTrackable", "classCaptain_1_1DMode_1_1IMultipleVehicleTrackable.html", [
      [ "Captain::DMode::ALC", "classCaptain_1_1DMode_1_1ALC.html", null ],
      [ "Captain::DMode::BLC", "classCaptain_1_1DMode_1_1BLC.html", null ],
      [ "Captain::DMode::CCF", "classCaptain_1_1DMode_1_1CCF.html", null ],
      [ "Captain::DMode::CF", "classCaptain_1_1DMode_1_1CF.html", null ],
      [ "Captain::DMode::DLC", "classCaptain_1_1DMode_1_1DLC.html", null ],
      [ "Captain::DMode::ELC", "classCaptain_1_1DMode_1_1ELC.html", null ],
      [ "Captain::DMode::LaneKeeping", "classCaptain_1_1DMode_1_1LaneKeeping.html", null ],
      [ "Captain::DMode::MCF", "classCaptain_1_1DMode_1_1MCF.html", null ],
      [ "Captain::DMode::Stop", "classCaptain_1_1DMode_1_1Stop.html", null ]
    ] ],
    [ "NextSimIO::InputAgentPax", "classNextSimIO_1_1InputAgentPax.html", null ],
    [ "NextSimIO::InputAgentPaxTrip", "classNextSimIO_1_1InputAgentPaxTrip.html", null ],
    [ "NextSimIO::InputAgents", "classNextSimIO_1_1InputAgents.html", null ],
    [ "NextSimIO::InputBackgroundTraffic", "classNextSimIO_1_1InputBackgroundTraffic.html", null ],
    [ "NextSimIO::InputDistribution", "classNextSimIO_1_1InputDistribution.html", null ],
    [ "NextSimIO::InputDRTStation", "classNextSimIO_1_1InputDRTStation.html", null ],
    [ "NextSimIO::InputEvent", "classNextSimIO_1_1InputEvent.html", null ],
    [ "NextSimIO::InputFlow", "classNextSimIO_1_1InputFlow.html", null ],
    [ "NextSimIO::InputGraphArc", "classNextSimIO_1_1InputGraphArc.html", null ],
    [ "NextSimIO::InputGraphVertex", "classNextSimIO_1_1InputGraphVertex.html", null ],
    [ "NextSimIO::InputLane", "classNextSimIO_1_1InputLane.html", null ],
    [ "NextSimIO::InputMessage", "classNextSimIO_1_1InputMessage.html", null ],
    [ "NextSimIO::InputMode", "classNextSimIO_1_1InputMode.html", null ],
    [ "NextSimIO::InputNode", "classNextSimIO_1_1InputNode.html", null ],
    [ "NextSimIO::InputODMatrix", "classNextSimIO_1_1InputODMatrix.html", null ],
    [ "NextSimIO::InputODPax", "classNextSimIO_1_1InputODPax.html", null ],
    [ "NextSimIO::InputPTline", "classNextSimIO_1_1InputPTline.html", null ],
    [ "InputrailLine", "classInputrailLine.html", null ],
    [ "NextSimIO::InputRailLine", "classNextSimIO_1_1InputRailLine.html", null ],
    [ "InputrailStaion", "classInputrailStaion.html", null ],
    [ "NextSimIO::InputRailStation", "classNextSimIO_1_1InputRailStation.html", null ],
    [ "NextSimIO::InputRecordMode", "classNextSimIO_1_1InputRecordMode.html", null ],
    [ "NextSimIO::InputScenario", "classNextSimIO_1_1InputScenario.html", null ],
    [ "NextSimIO::InputSegment", "classNextSimIO_1_1InputSegment.html", null ],
    [ "NextSimIO::InputSignal", "classNextSimIO_1_1InputSignal.html", null ],
    [ "NextSimIO::InputStation", "classNextSimIO_1_1InputStation.html", null ],
    [ "NextSimIO::InputTOD", "classNextSimIO_1_1InputTOD.html", null ],
    [ "NextSimIO::InputVehicleTypes", "classNextSimIO_1_1InputVehicleTypes.html", null ],
    [ "NextSimIO::intersectionPhase", "classNextSimIO_1_1intersectionPhase.html", null ],
    [ "Captain::Network::IVehicleContainableUnit", "structCaptain_1_1Network_1_1IVehicleContainableUnit.html", [
      [ "Captain::Network::GarageUnit", "classCaptain_1_1Network_1_1GarageUnit.html", null ],
      [ "Captain::Network::MesoUnit", "classCaptain_1_1Network_1_1MesoUnit.html", null ],
      [ "Captain::Network::MicroLane", "classCaptain_1_1Network_1_1MicroLane.html", null ],
      [ "Captain::Network::SinkUnit", "classCaptain_1_1Network_1_1SinkUnit.html", null ],
      [ "Captain::Network::SourceUnit", "classCaptain_1_1Network_1_1SourceUnit.html", null ]
    ] ],
    [ "Captain::IVehicleQueue", "classCaptain_1_1IVehicleQueue.html", [
      [ "Captain::SpinLockVehicleQueue", "classCaptain_1_1SpinLockVehicleQueue.html", null ],
      [ "Captain::Util::VehicleQueue", "classCaptain_1_1Util_1_1VehicleQueue.html", null ]
    ] ],
    [ "Captain::Util::JsonReader", "classCaptain_1_1Util_1_1JsonReader.html", null ],
    [ "Captain::Util::JsonRoute", "structCaptain_1_1Util_1_1JsonRoute.html", null ],
    [ "Captain::Util::JsonWriter", "classCaptain_1_1Util_1_1JsonWriter.html", null ],
    [ "LaneAccessType", "classLaneAccessType.html", null ],
    [ "LCDirection", "classLCDirection.html", null ],
    [ "NextSimIO::LinkArr", "classNextSimIO_1_1LinkArr.html", null ],
    [ "Captain::MesoComputationModel", "structCaptain_1_1MesoComputationModel.html", [
      [ "Captain::BasicMesoModel", "structCaptain_1_1BasicMesoModel.html", null ]
    ] ],
    [ "NextSimIO::MessageArr", "classNextSimIO_1_1MessageArr.html", null ],
    [ "NextSimIO::MetaData", "classNextSimIO_1_1MetaData.html", [
      [ "NextSimIO::InputCell", "classNextSimIO_1_1InputCell.html", null ],
      [ "NextSimIO::InputLink", "classNextSimIO_1_1InputLink.html", null ]
    ] ],
    [ "NextSimIO::ModeArr", "classNextSimIO_1_1ModeArr.html", null ],
    [ "Captain::ModeSequence", "classCaptain_1_1ModeSequence.html", null ],
    [ "Captain::NetInitializer", "classCaptain_1_1NetInitializer.html", null ],
    [ "NetworkType", "classNetworkType.html", null ],
    [ "Captain::Network::Node", "classCaptain_1_1Network_1_1Node.html", null ],
    [ "NextSimIO::NodeArr", "classNextSimIO_1_1NodeArr.html", null ],
    [ "Captain::NodeTurn", "structCaptain_1_1NodeTurn.html", null ],
    [ "ODMatrix", "classODMatrix.html", null ],
    [ "NextSimIO::ODMatrixArr", "classNextSimIO_1_1ODMatrixArr.html", null ],
    [ "OutputEventType", "classOutputEventType.html", null ],
    [ "NextSimIO::ParamArr", "classNextSimIO_1_1ParamArr.html", null ],
    [ "Captain::PassengerOld", "classCaptain_1_1PassengerOld.html", null ],
    [ "Captain::PassengerReservationInfo", "classCaptain_1_1PassengerReservationInfo.html", null ],
    [ "Captain::PassengerRoute", "structCaptain_1_1PassengerRoute.html", null ],
    [ "NextSimIO::PaxArr", "classNextSimIO_1_1PaxArr.html", null ],
    [ "Captain::PaxRoute", "structCaptain_1_1PaxRoute.html", null ],
    [ "Pedestrian", "classPedestrian.html", null ],
    [ "NextSimIO::phase", "classNextSimIO_1_1phase.html", null ],
    [ "NextSimIO::plan", "classNextSimIO_1_1plan.html", null ],
    [ "NextSimIO::port", "classNextSimIO_1_1port.html", null ],
    [ "NextSimIO::PTlineArr", "classNextSimIO_1_1PTlineArr.html", null ],
    [ "PTType", "classPTType.html", null ],
    [ "NextSimIO::RailLineArr", "classNextSimIO_1_1RailLineArr.html", null ],
    [ "Captain::RailPublicTransitInfo", "structCaptain_1_1RailPublicTransitInfo.html", null ],
    [ "NextSimIO::RailStationArr", "classNextSimIO_1_1RailStationArr.html", null ],
    [ "Captain::RandomDistribution< T >", "classCaptain_1_1RandomDistribution.html", [
      [ "Captain::NormalDistribution< double >", "classCaptain_1_1NormalDistribution.html", null ],
      [ "Captain::ExponentialDistribution< T >", "classCaptain_1_1ExponentialDistribution.html", null ],
      [ "Captain::NormalDistribution< T >", "classCaptain_1_1NormalDistribution.html", null ],
      [ "Captain::PoissonDistribution< T >", "classCaptain_1_1PoissonDistribution.html", null ],
      [ "Captain::UniformDistribution< T >", "classCaptain_1_1UniformDistribution.html", null ]
    ] ],
    [ "Captain::RandomEngine", "classCaptain_1_1RandomEngine.html", null ],
    [ "NextSimIO::RecordModeArr", "classNextSimIO_1_1RecordModeArr.html", null ],
    [ "Captain::RoadPublicTransitInfo", "structCaptain_1_1RoadPublicTransitInfo.html", null ],
    [ "Captain::RouteGenerator", "classCaptain_1_1RouteGenerator.html", null ],
    [ "Captain::RouteIdentifier", "structCaptain_1_1RouteIdentifier.html", null ],
    [ "RoutePreference", "classRoutePreference.html", null ],
    [ "NextSimIO::ScenarioArr", "classNextSimIO_1_1ScenarioArr.html", null ],
    [ "Captain::ScenarioInfo", "structCaptain_1_1ScenarioInfo.html", null ],
    [ "Captain::SharedObjectInfo", "structCaptain_1_1SharedObjectInfo.html", null ],
    [ "Captain::SharedPtr< T >", "classCaptain_1_1SharedPtr.html", null ],
    [ "Captain::SharedPtr< Captain::Network::MesoUnit >", "classCaptain_1_1SharedPtr.html", null ],
    [ "Captain::SharedPtr< Captain::Network::MicroLane >", "classCaptain_1_1SharedPtr.html", null ],
    [ "Captain::SharedPtr< Driver >", "classCaptain_1_1SharedPtr.html", null ],
    [ "Captain::SharedPtr< TRT >", "classCaptain_1_1SharedPtr.html", null ],
    [ "Captain::SharedSpinlock< T >", "classCaptain_1_1SharedSpinlock.html", null ],
    [ "Captain::Signal", "structCaptain_1_1Signal.html", null ],
    [ "NextSimIO::SignalArr", "classNextSimIO_1_1SignalArr.html", null ],
    [ "Captain::SignalController", "classCaptain_1_1SignalController.html", null ],
    [ "SignalMode", "classSignalMode.html", null ],
    [ "Captain::SignalPhase", "structCaptain_1_1SignalPhase.html", null ],
    [ "Captain::SpinLock< T >", "classCaptain_1_1SpinLock.html", null ],
    [ "Captain::SpinLockQueue< T >", "classCaptain_1_1SpinLockQueue.html", null ],
    [ "Captain::SpinLockQueue< Captain::SharedPtr >", "classCaptain_1_1SpinLockQueue.html", null ],
    [ "NextSimIO::StationArr", "classNextSimIO_1_1StationArr.html", null ],
    [ "Captain::StationExit", "structCaptain_1_1StationExit.html", null ],
    [ "Captain::StationInfo", "structCaptain_1_1StationInfo.html", [
      [ "Captain::RailStationInfo", "structCaptain_1_1RailStationInfo.html", null ],
      [ "Captain::RoadStationInfo", "structCaptain_1_1RoadStationInfo.html", null ]
    ] ],
    [ "Captain::StationPassengerList", "structCaptain_1_1StationPassengerList.html", null ],
    [ "Captain::SubtripIdentifier", "structCaptain_1_1SubtripIdentifier.html", null ],
    [ "SubtripMode", "classSubtripMode.html", null ],
    [ "NextSimIO::table", "classNextSimIO_1_1table.html", null ],
    [ "NextSimIO::timetable", "classNextSimIO_1_1timetable.html", null ],
    [ "Captain::Train", "classCaptain_1_1Train.html", null ],
    [ "NextSimIO::turn", "classNextSimIO_1_1turn.html", null ],
    [ "Captain::UnitConnectionDescriptor", "structCaptain_1_1UnitConnectionDescriptor.html", null ],
    [ "Captain::Network::UnitConnectionInfo", "structCaptain_1_1Network_1_1UnitConnectionInfo.html", null ],
    [ "Captain::UnitIdentifier", "structCaptain_1_1UnitIdentifier.html", null ],
    [ "UnitType", "classUnitType.html", null ],
    [ "Captain::User", "classCaptain_1_1User.html", [
      [ "Captain::Driver", "classCaptain_1_1Driver.html", null ],
      [ "Captain::Passenger", "classCaptain_1_1Passenger.html", null ]
    ] ],
    [ "Captain::UserDescriptor", "structCaptain_1_1UserDescriptor.html", null ],
    [ "Captain::UserInfo", "structCaptain_1_1UserInfo.html", null ],
    [ "Captain::UserState", "structCaptain_1_1UserState.html", null ],
    [ "Captain::UserStatistics", "structCaptain_1_1UserStatistics.html", null ],
    [ "Captain::UserTrip", "structCaptain_1_1UserTrip.html", null ],
    [ "UserType", "classUserType.html", null ],
    [ "Captain::V2X", "classCaptain_1_1V2X.html", null ],
    [ "Captain::Vehicle", "classCaptain_1_1Vehicle.html", [
      [ "Captain::TRT", "classCaptain_1_1TRT.html", null ]
    ] ],
    [ "Captain::VehicleDescriptor", "structCaptain_1_1VehicleDescriptor.html", null ],
    [ "VehicleDummyType", "classVehicleDummyType.html", null ],
    [ "Captain::VehicleInfo", "structCaptain_1_1VehicleInfo.html", null ],
    [ "Captain::VehiclePassengerList", "structCaptain_1_1VehiclePassengerList.html", null ],
    [ "Captain::VehicleReservationInfo", "classCaptain_1_1VehicleReservationInfo.html", null ],
    [ "Captain::VehicleRoute", "structCaptain_1_1VehicleRoute.html", null ],
    [ "Captain::VehicleState", "structCaptain_1_1VehicleState.html", null ],
    [ "Captain::VehicleStatistics", "structCaptain_1_1VehicleStatistics.html", null ],
    [ "VehicleType", "classVehicleType.html", null ],
    [ "NextSimIO::VehicleTypesArr", "classNextSimIO_1_1VehicleTypesArr.html", null ],
    [ "NextSimIO::VertexArr", "classNextSimIO_1_1VertexArr.html", null ],
    [ "NextSimIO::VertexCoord", "classNextSimIO_1_1VertexCoord.html", null ],
    [ "VertexCord", "classVertexCord.html", null ],
    [ "Captain::WeakPtr< T >", "classCaptain_1_1WeakPtr.html", null ],
    [ "Captain::Util::XmlWriter", "classCaptain_1_1Util_1_1XmlWriter.html", null ]
];